apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lmos-runtime.fullname" . }}-config
data:
  OPENAI_API_URL: {{ .Values.openaiApiUrl | quote }}
  OPENAI_API_MODEL: {{ .Values.openaiApiModel | quote }}
  OPENAI_API_TEMP: {{ .Values.openaiApiTemperature | quote }}
  OPENAI_API_FORMAT: {{ .Values.openaiApiFormat | quote }}
  OPENAI_API_MAX_TOKENS: {{ .Values.openaiApiMaxTokens | quote }}
  AGENT_REGISTRY_URL: {{ .Values.agentRegistryUrl | quote }}