#
# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
#

spring:
  application:
    name: lmos-runtime
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    org:
      springframework: WARN

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    metrics:
      access: read_only
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
