#
# // SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
# //
# // SPDX-License-Identifier: Apache-2.0
#

lmos:
  runtime:
    agent-registry:
    router:
      type: EXPLICIT
    cache:
      ttl: 6000
    cors:
      enabled: true
      allowed-headers:
        - "*"
      allowed-methods:
        - "*"
      allowed-origins:
        - "*"
      patterns:
        - "/**"
      max-age: 8000