{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "lmos-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.llmApiKey }}
  LLM_API_KEY: {{ .Values.llmApiKey | b64enc }}
  {{- end -}}

  {{- if .Values.embeddingModelApiKey }}
  EMBEDDING_MODEL_API_KEY: {{ .Values.embeddingModelApiKey | b64enc }}
  {{- end -}}

  {{- if .Values.embeddingStoreApiKey }}
  EMBEDDING_STORE_API_KEY: {{ .Values.embeddingStoreApiKey | b64enc }}
  {{- end -}}

{{- end }}