{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "lmos-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretKey }}: {{ .Values.secretApiKey | b64enc }}
{{- end }}