# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  packages: write
  contents: read
jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: gradle/actions/wrapper-validation@v4
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ghcr.io
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_NAMESPACE: lmos-ai
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build and push image to GitHub Packages
        run: ./gradlew bootBuildImage
      - name: Publish Chart to GitHub Packages
        run: ./gradlew helmPush